import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "../ui/dialog";
import { ScrollArea } from "../ui/scroll-area";

export function Terms({ children }: { children: React.ReactNode }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="max-w-2xl bg-slate-950 border-white/10 text-white max-h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>Terms of Service</DialogTitle>
        </DialogHeader>
        <ScrollArea className="flex-1 pr-4">
            <div className="space-y-4 text-gray-400 text-sm">
                <p>Last updated: March 15, 2024</p>
                <h3 className="text-white font-semibold text-base">1. Acceptance of Terms</h3>
                <p>
                    By accessing or using FlashFusion, you agree to be bound by these Terms of Service. 
                    If you do not agree to all the terms and conditions, you may not use our services.
                </p>
                <h3 className="text-white font-semibold text-base">2. Use License</h3>
                <p>
                    Permission is granted to temporarily download one copy of the materials (information or software) 
                    on FlashFusion's website for personal, non-commercial transitory viewing only.
                </p>
                <h3 className="text-white font-semibold text-base">3. Intellectual Property</h3>
                <p>
                    The code generated by FlashFusion from your designs is yours to own. 
                    However, the underlying platform, algorithms, and models remain the property of FlashFusion.
                </p>
                <h3 className="text-white font-semibold text-base">4. Disclaimer</h3>
                <p>
                    The materials on FlashFusion's website are provided on an 'as is' basis. 
                    FlashFusion makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties.
                </p>
                {/* Add more sections as needed */}
            </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
